name: Snake

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:
  push:
    branches:
    - master
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate github-snake.svg
        uses: ArthurLobopro/snk/svg-only@v0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?hide_stack=true&color_snake=#42313f&color_dots=#1f1826,#4a3651,#7a567b,#9f7d98,#bca9b4
            dist/github-snake-light.svg?hide_stack=true&color_snake=#1d1722&color_dots=#dbc7cd,#bfa0b0,#a17a98,#7b5c7b,#4f4153
      - name: push github-snake.svg and github-snake-light.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: github-snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
